### ISSUE TITLE
without docker?

### ISSUE THREAD

**Issue by chekanov** [AlonEirew/wikipedia-to-elastic#10]
This is an interesting project, but is any method to create elastic search index database without docker?  Docker is total overkill in this situation. It would be useful to have a simple description, i.e step 1) compile Java classes; 2) run WikiToElasticMain  java class to create indexes .

**Comment by AlonEirew** [comment]
Those instructions are included, refer to this [section](https://github.com/AlonEirew/wikipedia-to-elastic#building-the-index-from-source) in the readme file.

**Comment by chekanov** [comment]
Thanks! I've started looking into this. My first comment for Ubuntu users: 

` ./gradlew clean build -x test`

does not work. "./" means that "gradlew" is in the current directory.  But where can I find it?. Do you mean:

`gradle clean build -x test`

Ok, this can work assuming 'gradle" is installed in the standard location:  /usr/bin/gradle.

**Comment by AlonEirew** [comment]
You are right! I didn't commit the gradle wrapper. 
Fixed, after pull you should see the "gradlew" script for Ubuntu/Linux and gradlew.bat for windows :)
Thanks!

**Comment by chekanov** [comment]
Thanks a lot! This fixes it indeed. I can compile it. I still have one problem in running it. The error is:

```
INFO  wiki.WikiToElasticMain: Starting export Wiki dump to elastic process
Adding annotator tokenize
No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
14:57:50.646 [main] ERROR wiki.WikiToElasticMain: Something went wrong..
java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:245) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at wiki.data.relations.BeCompRelationExtractor.initResources(BeCompRelationExtractor.java:25) ~[WikipediaToElastic-1.0.jar:?]
	at wiki.WikiToElasticMain.main(WikiToElasticMain.java:38) [WikipediaToElastic-1.0.jar:?]
Caused by: edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:791) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:312) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:265) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(POSTaggerAnnotator.java:85) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.<init>(POSTaggerAnnotator.java:73) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(AnnotatorImplementations.java:63) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:243) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	... 7 more
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:470) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:789) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:312) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:265) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(POSTaggerAnnotator.java:85) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.POSTaggerAnnotator.<init>(POSTaggerAnnotator.java:73) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(AnnotatorImplementations.java:63) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:243) ~[stanford-corenlp-3.7.0.jar:3.7.0]
	... 7 more

```
Something is missing. My jar file WikipediaToElastic-1.0.jar has the size 50919. I've added it to my CLASSPATH where all Elasticsearch and 3rd party libraries are included and run it as:

`java -Xmx600m -DentityExpansionLimit=2147480000 -DtotalEntitySizeLimit=2147480000 -Djdk.xml.totalEntitySizeLimit=2147480000 -cp $CLASSPATH wiki.WikiToElasticMain`

Elastic search demon is running too.

Sergei

```

**Comment by AlonEirew** [comment]
You are missing the Stanford-CoreNLP jars
Did you try using the command as in the instructions (with -jar)? 
`java -Xmx6000m -DentityExpansionLimit=2147480000 -DtotalEntitySizeLimit=2147480000 -Djdk.xml.totalEntitySizeLimit=2147480000 -jar build/distributions/WikipediaToElastic-1.0/WikipediaToElastic-1.0.jar`

**Comment by chekanov** [comment]
Hi, Alon

 My directory "build/distributions/" had only zip and tar file. Ok, I've unzipped and I've got WikipediaToElastic-1.0/WikipediaToElastic-1.0.jar and "lib" with a bunch of jar file. Then 
I put all jar files from lib to my Java CLASSPATH, and  I ran this command on the small xml.gz dump file you provide. It works, but after 30 second, it said "out of memory".

Ok, it works if I run it like this:

`java  -jar /build/distributions/WikipediaToElastic-1.0/WikipediaToElastic-1.0.jar`

it's very slow, about 1 page per 1sec. I feel there is  a massive overhead somewhere. Some pages fail:

```
10:45:54.499 [pool-3-thread-3] INFO  wiki.parsers.STAXParser: prepare to commit page with id-91, title-Datu puorlaida
Exception in thread "I/O dispatcher 1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:212)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```





```

**Comment by AlonEirew** [comment]
1) Regarding the OutOfMemoryError error, in order to fix this you need to add the command parameters (eg. `-Xmx6000m -DentityExpansionLimit=2147480000 -DtotalEntitySizeLimit=2147480000 -Djdk.xml.totalEntitySizeLimit=2147480000`)

2) Regarding the slow performance, if you didn't set the normalize parameter (`normalizeFields`) in the configuration (`conf.json`) to `false`, the process will lemmatize all fields (changing verbs to their root, eg. 'running' -> 'run'), if this is something that you don't need, you can change it in the configuration in order to make the process run much faster. 

3) In case normalization is needed for your project, another option is to use the docker image (which has everything prepared and will save you that time)</t>
